### ISSUE TITLE
Fixing legend of graph

### ISSUE THREAD

**Issue by luismanriqueruiz** [sanghvirajit/Feedforward_Neural_Network#1]
Not an issue but a typo. I just noticed that in one of your pictures it is written "RMPprop",  I believe you meant "RMSprop", right?.

**Comment by sanghvirajit** [comment]
@luismanriqueruiz Thank you for letting me know, I corrected it. :+1:

**Comment by luismanriqueruiz** [comment]
Good job by the way!
